### ISSUE TITLE
Syntax error when running

### ISSUE THREAD

**Issue by byhag** [JBKLabs/create-react-app#6]
## Description

Below is the console output.

```
$ create-react-app test-react-app
/usr/local/lib/node_modules/@jbknowledge/create-react-app/index.js:68
      } catch {}
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

## Steps to Recreate

- Use `npx` or install globally and run (on a Mac?)

**Comment by byhag** [comment]
Appears to be Mac specific
